### ISSUE TITLE
[Question] I would like to port your mod to forge

### ISSUE THREAD

**Issue by PlatinPython** [MCrafterzz/Rgb-Blocks#3]
A lot of people really seem to want a forge version of your mod, me included, and since you said you wouldn't make one, I thought that I could make one. As long as you're fine with that.

I will of course mark it as a port and link back to your mod.

**Comment by PlatinPython** [comment]
Or if you don't want a port I would at least like to use your textures

**Comment by MarcusElg** [comment]
Yes you can port it. I would appreciate if you linked back to the original mod and gave me a small split of the curse points. Not a requirement tho

**Comment by PlatinPython** [comment]
Alright then, thank you
